# Generated by Django 4.2 on 2023-05-12 15:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_article_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=2000)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=users.models.upload_to)),
            ],
        ),
    ]
